<?php
/**
 * Monster Table
 * @extends FCDBTableCreation
 * @extends FCDBTableInteraction
 *
 * Table Name: monsters
 * Table Schema:
 *
 * 		COLUMN                 Data Type               Defualt
 * 		---------------        ---------------         ---------------
 * 		ID                     INT(6)                  N/A
 * 		name                   VARCHAR(255)            NULL (NOT NULL)
 * 		size                   VARCHAR(255)            NULL (NOT NULL)
 * 		type                   VARCHAR(255)            NULL (NOT NULL)
 * 		tags                   VARCHAR(255)            NULL (NOT NULL)
 * 		alignment              VARCHAR(255)            NULL (NOT NULL)
 * 		challenge              DOUBLE                  NULL (NOT NULL)
 * 		xp                     INT(6)                  NULL (NOT NULL)
 * 		source                 VARCHAR(255)            NULL (NOT NULL)
 *
 *
 */
class FCMonsterTable extends FCDBTableInteraction {

    public function __construct() {
        $name = 'monsters';
        $columns = array(
            array( 'name',              'VARCHAR(255)',           'NOT NULL' ),
            array( 'size',              'VARCHAR(255)',           'NOT NULL' ),
            array( 'type',              'VARCHAR(255)',           'NOT NULL' ),
            array( 'tags',              'VARCHAR(255)',           'NOT NULL' ),
            array( 'alignment',         'VARCHAR(255)',           'NOT NULL' ),
            array( 'challenge',         'DOUBLE',                 'NOT NULL' ),
            array( 'xp',                'INT(6)',                 'NOT NULL' ),
            array( 'source',            'VARCHAR(255)',           'NOT NULL' ),
        );

        $this->defaults = array(
            'name' => NULL,
            'size' => NULL,
            'type' => NULL,
            'tags' => NULL,
            'alignment' => NULL,
            'challenge' => NULL,
            'xp' => NULL,
            'source' => NULL,
        );

        $this->name = $name;
        $this->cols = $columns;

        $r = parent::__construct();
        $this->reset();

        if ($r) {
            $this->populate();
        }
    }

    public function populate() {
        $v = array(
            array("Frog", "Tiny", "Beast", "Unaligned", "0", "0", "mm", "322"),
            array("Sea Horse", "Tiny", "Beast", "Unaligned", "0", "0", "mm", "337"),
            array("Awakened Shrub", "Small", "Plant", "Unaligned", "0", "10", "mm", "317"),
            array("Baboon", "Small", "Beast", "Unaligned", "0", "10", "mm", "318"),
            array("Badger", "Tiny", "Beast", "Unaligned", "0", "10", "mm", "318"),
            array("Bat", "Tiny", "Beast", "Unaligned", "0", "10", "mm", "318"),
            array("Cat", "Tiny", "Beast", "Unaligned", "0", "10", "mm", "320"),
            array("Crab", "Tiny", "Beast", "Unaligned", "0", "10", "mm", "320"),
            array("Crawling Claw", "Tiny", "Undead", "NE", "0", "10", "mm", "44"),
            array("Deer", "Medium", "Beast", "Unaligned", "0", "10", "mm", "321"),
            array("Eagle", "Small", "Beast", "Unaligned", "0", "10", "mm", "322"),
            array("Giant Fire Beetle", "Small", "Beast", "Unaligned", "0", "10", "mm", "325"),
            array("Goat", "Medium", "Beast", "Unaligned", "0", "10", "mm", "330"),
            array("Hawk", "Tiny", "Beast", "Unaligned", "0", "10", "mm", "330"),
            array("Homunculus", "Tiny", "Construct", "N", "0", "10", "mm", "188"),
            array("Hyena", "Medium", "Beast", "Unaligned", "0", "10", "mm", "331"),
            array("Jackal", "Small", "Beast", "Unaligned", "0", "10", "mm", "331"),
            array("Lemure", "Medium", "Fiend", "devil", "LE", "0", "10", "mm", "76"),
            array("Lizard", "Tiny", "Beast", "Unaligned", "0", "10", "mm", "332"),
            array("Myconid Sprout", "Small", "Plant", "LN", "0", "10", "mm", "230"),
            array("Octopus", "Small", "Beast", "Unaligned", "0", "10", "mm", "333"),
            array("Owl", "Tiny", "Beast", "Unaligned", "0", "10", "mm", "333"),
            array("Quipper", "Tiny", "Beast", "Unaligned", "0", "10", "mm", "335"),
            array("Rat", "Tiny", "Beast", "Unaligned", "0", "10", "mm", "335"),
            array("Raven", "Tiny", "Beast", "Unaligned", "0", "10", "mm", "335"),
            array("Scorpion", "Tiny", "Beast", "Unaligned", "0", "10", "mm", "337"),
            array("Shrieker", "Medium", "Plant", "Unaligned", "0", "10", "mm", "138"),
            array("Spider", "Tiny", "Beast", "Unaligned", "0", "10", "mm", "337"),
            array("Vulture", "Medium", "Beast", "Unaligned", "0", "10", "mm", "339"),
            array("Weasel", "Tiny", "Beast", "Unaligned", "0", "10", "mm", "340"),
            array("Blood Hawk", "Small", "Beast", "Unaligned", "0.125", "25", "mm", "319"),
            array("Camel", "Large", "Beast", "Unaligned", "0.125", "25", "mm", "320"),
            array("Flumph", "Small", "Aberration", "LG", "0.125", "25", "mm", "135"),
            array("Flying Snake", "Tiny", "Beast", "Unaligned", "0.125", "25", "mm", "322"),
            array("Giant Crab", "Medium", "Beast", "Unaligned", "0.125", "25", "mm", "324"),
            array("Giant Rat", "Small", "Beast", "Unaligned", "0.125", "25", "mm", "327"),
            array("Giant Weasel", "Medium", "Beast", "Unaligned", "0.125", "25", "mm", "329"),
            array("Kobold", "Small", "Humanoid", "kobold", "LE", "0.125", "25", "mm", "195"),
            array("Manes", "Small", "Fiend", "demon", "CE", "0.125", "25", "mm", "60"),
            array("Mastiff", "Medium", "Beast", "Unaligned", "0.125", "25", "mm", "332"),
            array("Merfolk", "Medium", "Humanoid", "merfolk", "N", "0.125", "25", "mm", "218"),
            array("Monodrone", "Medium", "Construct", "LN", "0.125", "25", "mm", "224"),
            array("Mule", "Medium", "Beast", "Unaligned", "0.125", "25", "mm", "333"),
            array("Poisonous Snake", "Tiny", "Beast", "Unaligned", "0.125", "25", "mm", "334"),
            array("Pony", "Medium", "Beast", "Unaligned", "0.125", "25", "mm", "335"),
            array("Slaad Tadpole", "Tiny", "Aberration", "CN", "0.125", "25", "mm", "276"),
            array("Stirge", "Tiny", "Beast", "Unaligned", "0.125", "25", "mm", "284"),
            array("Twig Blight", "Small", "Plant", "NE", "0.125", "25", "mm", "32"),
            array("Aarakocra", "Medium", "Humanoid", "aarakocra", "NG", "0.25", "50", "mm", "12"),
            array("Axe Beak", "Large", "Beast", "Unaligned", "0.25", "50", "mm", "317"),
            array("Blink Dog", "Medium", "Fey", "LG", "0.25", "50", "mm", "318"),
            array("Boar", "Medium", "Beast", "Unaligned", "0.25", "50", "mm", "319"),
            array("Bullywug", "Medium", "Humanoid", "bullywug", "NE", "0.25", "50", "mm", "35"),
            array("Constrictor Snake", "Large", "Beast", "Unaligned", "0.25", "50", "mm", "320"),
            array("Draft Horse", "Large", "Beast", "Unaligned", "0.25", "50", "mm", "321"),
            array("Dretch", "Small", "Fiend", "demon", "CE", "0.25", "50", "mm", "57"),
            array("Drow", "Medium", "Humanoid", "elf", "NE", "0.25", "50", "mm", "128"),
            array("Duodrone", "Medium", "Construct", "LN", "0.25", "50", "mm", "225"),
            array("Elk", "Large", "Beast", "Unaligned", "0.25", "50", "mm", "322"),
            array("Flying Sword", "Small", "Construct", "Unaligned", "0.25", "50", "mm", "20"),
            array("Giant Badger", "Medium", "Beast", "Unaligned", "0.25", "50", "mm", "323"),
            array("Giant Bat", "Large", "Beast", "Unaligned", "0.25", "50", "mm", "323"),
            array("Giant Centipede", "Small", "Beast", "Unaligned", "0.25", "50", "mm", "323"),
            array("Giant Frog", "Medium", "Beast", "Unaligned", "0.25", "50", "mm", "325"),
            array("Giant Lizard", "Large", "Beast", "Unaligned", "0.25", "50", "mm", "326"),
            array("Giant Owl", "Large", "Beast", "N", "0.25", "50", "mm", "327"),
            array("Giant Poisonous Snake", "Medium", "Beast", "Unaligned", "0.25", "50", "mm", "327"),
            array("Giant Wolf Spider", "Medium", "Beast", "Unaligned", "0.25", "50", "mm", "330"),
            array("Goblin", "Small", "Humanoid", "goblinoid", "NE", "0.25", "50", "mm", "166"),
            array("Grimlock", "Medium", "Humanoid", "grimlock", "NE", "0.25", "50", "mm", "175"),
            array("Kenku", "Medium", "Humanoid", "kenku", "CN", "0.25", "50", "mm", "194"),
            array("Kuo-toa", "Medium", "Humanoid", "kuo-toa", "NE", "0.25", "50", "mm", "199"),
            array("Mud Mephit", "Small", "Elemental", "NE", "0.25", "50", "mm", "216"),
            array("Needle Blight", "Medium", "Plant", "NE", "0.25", "50", "mm", "32"),
            array("Panther", "Medium", "Beast", "Unaligned", "0.25", "50", "mm", "333"),
            array("Pixie", "Tiny", "Fey", "NG", "0.25", "50", "mm", "253"),
            array("Pseudodragon", "Tiny", "Dragon", "NG", "0.25", "50", "mm", "254"),
            array("Pteranodon", "Medium", "Beast", "Unaligned", "0.25", "50", "mm", "80"),
            array("Riding Horse", "Large", "Beast", "Unaligned", "0.25", "50", "mm", "336"),
            array("Skeleton", "Medium", "Undead", "LE", "0.25", "50", "mm", "272"),
            array("Smoke Mephit", "Small", "Elemental", "NE", "0.25", "50", "mm", "217"),
            array("Sprite", "Tiny", "Fey", "NG", "0.25", "50", "mm", "283"),
            array("Steam Mephit", "Small", "Elemental", "NE", "0.25", "50", "mm", "217"),
            array("Swarm of Bats", "Medium", "Beast", "Unaligned", "0.25", "50", "mm", "337"),
            array("Swarm of Rats", "Medium", "Beast", "Unaligned", "0.25", "50", "mm", "339"),
            array("Swarm of Ravens", "Medium", "Beast", "Unaligned", "0.25", "50", "mm", "339"),
            array("Troglodyte", "Medium", "Humanoid", "troglodyte", "CE", "0.25", "50", "mm", "290"),
            array("Violet Fungus", "Medium", "Plant", "Unaligned", "0.25", "50", "mm", "138"),
            array("Winged Kobold", "Small", "Humanoid", "kobold", "LE", "0.25", "50", "mm", "195"),
            array("Wolf", "Medium", "Beast", "Unaligned", "0.25", "50", "mm", "341"),
            array("Zombie", "Medium", "Undead", "NE", "0.25", "50", "mm", "316"),
            array("Ape", "Medium", "Beast", "Unaligned", "0.5", "100", "mm", "317"),
            array("Black Bear", "Medium", "Beast", "Unaligned", "0.5", "100", "mm", "318"),
            array("Cockatrice", "Small", "Monstrosity", "Unaligned", "0.5", "100", "mm", "42"),
            array("Crocodile", "Large", "Beast", "Unaligned", "0.5", "100", "mm", "320"),
            array("Darkmantle", "Small", "Monstrosity", "Unaligned", "0.5", "100", "mm", "46"),
            array("Dust Mephit", "Small", "Elemental", "NE", "0.5", "100", "mm", "215"),
            array("Gas Spore", "Large", "Plant", "Unaligned", "0.5", "100", "mm", "138"),
            array("Giant Goat", "Large", "Beast", "Unaligned", "0.5", "100", "mm", "326"),
            array("Giant Sea Horse", "Large", "Beast", "Unaligned", "0.5", "100", "mm", "328"),
            array("Giant Wasp", "Medium", "Beast", "Unaligned", "0.5", "100", "mm", "329"),
            array("Gnoll", "Medium", "Humanoid", "gnoll", "CE", "0.5", "100", "mm", "163"),
            array("Gray Ooze", "Medium", "Ooze", "Unaligned", "0.5", "100", "mm", "243"),
            array("Hobgoblin", "Medium", "Humanoid", "goblinoid", "LE", "0.5", "100", "mm", "186"),
            array("Ice Mephit", "Small", "Elemental", "NE", "0.5", "100", "mm", "215"),
            array("Jackalwere", "Medium", "Humanoid", "shapechanger", "CE", "0.5", "100", "mm", "193"),
            array("Lizardfolk", "Medium", "Humanoid", "lizardfolk", "N", "0.5", "100", "mm", "204"),
            array("Magma Mephit", "Small", "Elemental", "NE", "0.5", "100", "mm", "216"),
            array("Magmin", "Small", "Elemental", "CN", "0.5", "100", "mm", "212"),
            array("Myconid Adult", "Medium", "Plant", "LN", "0.5", "100", "mm", "232"),
            array("Orc", "Medium", "Humanoid", "orc", "CE", "0.5", "100", "mm", "246"),
            array("Piercer", "Medium", "Monstrosity", "Unaligned", "0.5", "100", "mm", "252"),
            array("Reef Shark", "Medium", "Beast", "Unaligned", "0.5", "100", "mm", "336"),
            array("Rust Monster", "Medium", "Monstrosity", "Unaligned", "0.5", "100", "mm", "262"),
            array("Sahuagin", "Medium", "Humanoid", "sahuagin", "LE", "0.5", "100", "mm", "263"),
            array("Satyr", "Medium", "Fey", "CN", "0.5", "100", "mm", "267"),
            array("Shadow", "Medium", "Undead", "CE", "0.5", "100", "mm", "269"),
            array("Svirfneblin", "Small", "Humanoid", "gnome", "NG", "0.5", "100", "mm", "164"),
            array("Swarm of Insects", "Medium", "Beast", "Unaligned", "0.5", "100", "mm", "338"),
            array("Tridrone", "Medium", "Construct", "LN", "0.5", "100", "mm", "225"),
            array("Vine Blight", "Medium", "Plant", "NE", "0.5", "100", "mm", "32"),
            array("Warhorse", "Large", "Beast", "Unaligned", "0.5", "100", "mm", "340"),
            array("Warhorse Skeleton", "Large", "Undead", "LE", "0.5", "100", "mm", "273"),
            array("Worg", "Large", "Monstrosity", "NE", "0.5", "100", "mm", "341"),
            array("Animated Armor", "Medium", "Construct", "Unaligned", "1", "200", "mm", "19"),
            array("Brass Dragon Wyrmling", "Medium", "Dragon", "CG", "1", "200", "mm", "106"),
            array("Brown Bear", "Large", "Beast", "Unaligned", "1", "200", "mm", "319"),
            array("Bugbear", "Medium", "Humanoid", "goblinoid", "CE", "1", "200", "mm", "33"),
            array("Copper Dragon Wyrmling", "Medium", "Dragon", "CG", "1", "200", "mm", "112"),
            array("Death Dog", "Medium", "Monstrosity", "NE", "1", "200", "mm", "321"),
            array("Dire Wolf", "Large", "Beast", "Unaligned", "1", "200", "mm", "321"),
            array("Dryad", "Medium", "Fey", "N", "1", "200", "mm", "121"),
            array("Duergar", "Medium", "Humanoid", "dwarf", "LE", "1", "200", "mm", "122"),
            array("Fire Snake", "Medium", "Elemental", "NE", "1", "200", "mm", "265"),
            array("Ghoul", "Medium", "Undead", "CE", "1", "200", "mm", "148"),
            array("Giant Eagle", "Large", "Beast", "NG", "1", "200", "mm", "324"),
            array("Giant Hyena", "Large", "Beast", "Unaligned", "1", "200", "mm", "326"),
            array("Giant Octopus", "Large", "Beast", "Unaligned", "1", "200", "mm", "326"),
            array("Giant Spider", "Large", "Beast", "Unaligned", "1", "200", "mm", "328"),
            array("Giant Toad", "Large", "Beast", "Unaligned", "1", "200", "mm", "329"),
            array("Giant Vulture", "Large", "Beast", "NE", "1", "200", "mm", "329"),
            array("Goblin Boss", "Small", "Humanoid", "goblinoid", "NE", "1", "200", "mm", "166"),
            array("Half-ogre", "Large", "Giant", "Any chaotic", "1", "200", "mm", "238"),
            array("Harpy", "Medium", "Monstrosity", "CE", "1", "200", "mm", "181"),
            array("Hippogriff", "Large", "Monstrosity", "Unaligned", "1", "200", "mm", "184"),
            array("Imp", "Tiny", "Fiend", "devil, shapechanger", "LE", "1", "200", "mm", "76"),
            array("Kuo-toa Whip", "Medium", "Humanoid", "kuo-toa", "NE", "1", "200", "mm", "200"),
            array("Lion", "Large", "Beast", "Unaligned", "1", "200", "mm", "331"),
            array("Quadrone", "Medium", "Construct", "LN", "1", "200", "mm", "226"),
            array("Quaggoth Spore Servant", "Medium", "Plant", "Unaligned", "1", "200", "mm", "230"),
            array("Quasit", "Tiny", "Fiend", "demon, shapechanger", "CE", "1", "200", "mm", "63"),
            array("Scarecrow", "Medium", "Construct", "CE", "1", "200", "mm", "268"),
            array("Specter", "Medium", "Undead", "CE", "1", "200", "mm", "279"),
            array("Swarm of Quippers", "Medium", "Beast", "Unaligned", "1", "200", "mm", "338"),
            array("Thri-kreen", "Medium", "Humanoid", "thri-kreen", "CN", "1", "200", "mm", "288"),
            array("Tiger", "Large", "Beast", "Unaligned", "1", "200", "mm", "339"),
            array("Young Faerie Dragon", "Tiny", "Dragon", "CG", "1", "200", "mm", "133"),
            array("Yuan-ti Pureblood", "Medium", "Humanoid", "yuan-ti", "NE", "1", "200", "mm", "310"),
            array("Adult Faerie Dragon", "Tiny", "Dragon", "CG", "2", "450", "mm", "133"),
            array("Allosaurus", "Large", "Beast", "Unaligned", "2", "450", "mm", "79"),
            array("Ankheg", "Large", "Monstrosity", "Unaligned", "2", "450", "mm", "21"),
            array("Awakened Tree", "Huge", "Plant", "Unaligned", "2", "450", "mm", "317"),
            array("Azer", "Medium", "Elemental", "LN", "2", "450", "mm", "22"),
            array("Black Dragon Wyrmling", "Medium", "Dragon", "CE", "2", "450", "mm", "88"),
            array("Bronze Dragon Wyrmling", "Medium", "Dragon", "LG", "2", "450", "mm", "109"),
            array("Carrion Crawler", "Large", "Monstrosity", "Unaligned", "2", "450", "mm", "37"),
            array("Cave Bear", "Large", "Beast", "Unaligned", "2", "450", "mm", "334"),
            array("Centaur", "Large", "Monstrosity", "NG", "2", "450", "mm", "38"),
            array("Ettercap", "Medium", "Monstrosity", "NE", "2", "450", "mm", "131"),
            array("Gargoyle", "Medium", "Elemental", "CE", "2", "450", "mm", "140"),
            array("Gelatinous Cube", "Large", "Ooze", "Unaligned", "2", "450", "mm", "242"),
            array("Ghast", "Medium", "Undead", "CE", "2", "450", "mm", "148"),
            array("Giant Boar", "Large", "Beast", "Unaligned", "2", "450", "mm", "323"),
            array("Giant Constrictor Snake", "Huge", "Beast", "Unaligned", "2", "450", "mm", "324"),
            array("Giant Elk", "Huge", "Beast", "Unaligned", "2", "450", "mm", "325"),
            array("Gibbering Mouther", "Medium", "Aberration", "N", "2", "450", "mm", "157"),
            array("Githzerai Monk", "Medium", "Humanoid", "gith", "LN", "2", "450", "mm", "161"),
            array("Gnoll Pack Lord", "Medium", "Humanoid", "gnoll", "CE", "2", "450", "mm", "163"),
            array("Green Dragon Wyrmling", "Medium", "Dragon", "LE", "2", "450", "mm", "95"),
            array("Grick", "Medium", "Monstrosity", "N", "2", "450", "mm", "173"),
            array("Griffon", "Large", "Monstrosity", "Unaligned", "2", "450", "mm", "174"),
            array("Hunter Shark", "Large", "Beast", "Unaligned", "2", "450", "mm", "330"),
            array("Intellect Devourer", "Tiny", "Aberration", "LE", "2", "450", "mm", "191"),
            array("Lizardfolk Shaman", "Medium", "Humanoid", "lizardfolk", "N", "2", "450", "mm", "205"),
            array("Merrow", "Large", "Monstrosity", "CE", "2", "450", "mm", "219"),
            array("Mimic", "Medium", "Monstrosity", "shapechanger", "N", "2", "450", "mm", "220"),
            array("Minotaur Skeleton", "Large", "Undead", "LE", "2", "450", "mm", "273"),
            array("Myconid Sovereign", "Large", "Plant", "LN", "2", "450", "mm", "232"),
            array("Nothic", "Medium", "Aberration", "NE", "2", "450", "mm", "236"),
            array("Ochre Jelly", "Large", "Ooze", "Unaligned", "2", "450", "mm", "243"),
            array("Ogre", "Large", "Giant", "CE", "2", "450", "mm", "237"),
            array("Ogre Zombie", "Large", "Undead", "NE", "2", "450", "mm", "316"),
            array("Orc Eye of Gruumsh", "Medium", "Humanoid", "orc", "CE", "2", "450", "mm", "247"),
            array("Orog", "Medium", "Humanoid", "orc", "CE", "2", "450", "mm", "247"),
            array("Pegasus", "Large", "Celestial", "CG", "2", "450", "mm", "250"),
            array("Pentadrone", "Large", "Construct", "LN", "2", "450", "mm", "226"),
            array("Peryton", "Medium", "Monstrosity", "CE", "2", "450", "mm", "251"),
            array("Plesiosaurus", "Large", "Beast", "Unaligned", "2", "450", "mm", "80"),
            array("Polar Bear", "Large", "Beast", "Unaligned", "2", "450", "mm", "334"),
            array("Quaggoth", "Medium", "Humanoid", "quaggoth", "CN", "2", "450", "mm", "256"),
            array("Rhinoceros", "Large", "Beast", "Unaligned", "2", "450", "mm", "336"),
            array("Rug of Smothering", "Large", "Construct", "Unaligned", "2", "450", "mm", "20"),
            array("Saber-toothed Tiger", "Large", "Beast", "Unaligned", "2", "450", "mm", "336"),
            array("Sahuagin Priestess", "Medium", "Humanoid", "sahuagin", "LE", "2", "450", "mm", "264"),
            array("Sea Hag", "Medium", "Fey", "CE", "2", "450", "mm", "179"),
            array("Silver Dragon Wyrmling", "Medium", "Dragon", "LG", "2", "450", "mm", "118"),
            array("Specter (poltergeist)", "Medium", "Undead", "CE", "2", "450", "mm", "279"),
            array("Spined Devil", "Small", "Fiend", "devil", "LE", "2", "450", "mm", "78"),
            array("Swarm of Poisonous Snakes", "Medium", "Beast", "Unaligned", "2", "450", "mm", "338"),
            array("Wererat", "Medium", "Humanoid", "Human, Shapeshifter", "LE", "2", "450", "mm", "209"),
            array("White Dragon Wyrmling", "Medium", "Dragon", "CE", "2", "450", "mm", "102"),
            array("Will-o-wisp", "Tiny", "Undead", "CE", "2", "450", "mm", "301"),
            array("Ankylosaurus", "Huge", "Beast", "Unaligned", "3", "700", "mm", "79"),
            array("Basilisk", "Medium", "Monstrosity", "Unaligned", "3", "700", "mm", "24"),
            array("Bearded Devil", "Medium", "Fiend", "devil", "LE", "3", "700", "mm", "70"),
            array("Blue Dragon Wyrmling", "Medium", "Dragon", "LE", "3", "700", "mm", "91"),
            array("Bugbear Chief", "Medium", "Humanoid", "goblinoid", "CE", "3", "700", "mm", "33"),
            array("Displacer Beast", "Large", "Monstrosity", "LE", "3", "700", "mm", "81"),
            array("Doppelganger", "Medium", "Monstrosity", "shapechanger", "N", "3", "700", "mm", "82"),
            array("Giant Scorpion", "Large", "Beast", "Unaligned", "3", "700", "mm", "327"),
            array("Githyanki Warrior", "Medium", "Humanoid", "gith", "LE", "3", "700", "mm", "160"),
            array("Gold Dragon Wyrmling", "Medium", "Dragon", "LG", "3", "700", "mm", "115"),
            array("Green Hag", "Medium", "Fey", "NE", "3", "700", "mm", "177"),
            array("Grell", "Medium", "Aberration", "NE", "3", "700", "mm", "172"),
            array("Hell Hound", "Medium", "Fiend", "LE", "3", "700", "mm", "182"),
            array("Hobgoblin Captain", "Medium", "Humanoid", "goblinoid", "LE", "3", "700", "mm", "186"),
            array("Hook Horror", "Large", "Monstrosity", "N", "3", "700", "mm", "189"),
            array("Killer Whale", "Huge", "Beast", "Unaligned", "3", "700", "mm", "331"),
            array("Manticore", "Large", "Monstrosity", "LE", "3", "700", "mm", "213"),
            array("Minotaur", "Large", "Monstrosity", "CE", "3", "700", "mm", "223"),
            array("Mummy", "Medium", "Undead", "LE", "3", "700", "mm", "228"),
            array("Nightmare", "Large", "Fiend", "NE", "3", "700", "mm", "235"),
            array("Owlbear", "Large", "Monstrosity", "Unaligned", "3", "700", "mm", "249"),
            array("Phase Spider", "Large", "Monstrosity", "Unaligned", "3", "700", "mm", "334"),
            array("Quaggoth Thonot", "Medium", "Humanoid", "quaggoth", "CN", "3", "700", "mm", "256"),
            array("Spectator", "Medium", "Aberration", "LN", "3", "700", "mm", "30"),
            array("Water Weird", "Large", "Elemental", "N", "3", "700", "mm", "299"),
            array("Werewolf", "Medium", "Humanoid", "Human, Shapeshifter", "CE", "3", "700", "mm", "211"),
            array("Wight", "Medium", "Undead", "NE", "3", "700", "mm", "300"),
            array("Winter Wolf", "Large", "Monstrosity", "NE", "3", "700", "mm", "340"),
            array("Yeti", "Large", "Monstrosity", "CE", "3", "700", "mm", "305"),
            array("Yuan-ti Malison", "Medium", "Monstrosity", "shapechanger, yuan-ti", "NE", "3", "700", "mm", "309"),
            array("Banshee", "Medium", "Undead", "CE", "4", "1100", "mm", "23"),
            array("Black Pudding", "Large", "Ooze", "Unaligned", "4", "1100", "mm", "241"),
            array("Bone Naga", "Large", "Undead", "LE", "4", "1100", "mm", "233"),
            array("Chuul", "Large", "Aberration", "CE", "4", "1100", "mm", "40"),
            array("Couatl", "Medium", "Celestial", "LG", "4", "1100", "mm", "43"),
            array("Elephant", "Huge", "Beast", "Unaligned", "4", "1100", "mm", "322"),
            array("Ettin", "Large", "Giant", "CE", "4", "1100", "mm", "132"),
            array("Flameskull", "Tiny", "Undead", "NE", "4", "1100", "mm", "134"),
            array("Ghost", "Medium", "Undead", "Any", "4", "1100", "mm", "147"),
            array("Gnoll Fang of Yeenoghu", "Medium", "Fiend", "gnoll", "CE", "4", "1100", "mm", "163"),
            array("Helmed Horror", "Medium", "Construct", "N", "4", "1100", "mm", "183"),
            array("Incubus", "Medium", "Fiend", "shapechanger", "NE", "4", "1100", "mm", "285"),
            array("Lamia", "Large", "Monstrosity", "CE", "4", "1100", "mm", "201"),
            array("Lizard King/Queen", "Medium", "Humanoid", "lizardfolk", "CE", "4", "1100", "mm", "205"),
            array("Orc War Chief", "Medium", "Humanoid", "orc", "CE", "4", "1100", "mm", "246"),
            array("Red Dragon Wyrmling", "Medium", "Dragon", "CE", "4", "1100", "mm", "98"),
            array("Shadow Demon", "Medium", "Fiend", "demon", "CE", "4", "1100", "mm", "64"),
            array("Succubus", "Medium", "Fiend", "shapechanger", "NE", "4", "1100", "mm", "285"),
            array("Wereboar", "Medium", "Humanoid", "human, shapechanger", "NE", "4", "1100", "mm", "209"),
            array("Weretiger", "Medium", "Humanoid", "human, shapechanger", "N", "4", "1100", "mm", "210"),
            array("Air Elemental", "Large", "Elemental", "N", "5", "1800", "mm", "124"),
            array("Barbed Devil", "Medium", "Fiend", "devil", "LE", "5", "1800", "mm", "70"),
            array("Barlgura", "Large", "Fiend", "demon", "CE", "5", "1800", "mm", "56"),
            array("Beholder Zombie", "Large", "Undead", "NE", "5", "1800", "mm", "316"),
            array("Bulette", "Large", "Monstrosity", "Unaligned", "5", "1800", "mm", "34"),
            array("Cambion", "Medium", "Fiend", "Any evil", "5", "1800", "mm", "36"),
            array("Drow Elite Warrior", "Medium", "Humanoid", "elf", "NE", "5", "1800", "mm", "128"),
            array("Earth Elemental", "Large", "Elemental", "N", "5", "1800", "mm", "124"),
            array("Fire Elemental", "Large", "Elemental", "N", "5", "1800", "mm", "125"),
            array("Flesh Golem", "Medium", "Construct", "N", "5", "1800", "mm", "169"),
            array("Giant Crocodile", "Huge", "Beast", "Unaligned", "5", "1800", "mm", "324"),
            array("Giant Shark", "Huge", "Beast", "Unaligned", "5", "1800", "mm", "328"),
            array("Gorgon", "Large", "Monstrosity", "Unaligned", "5", "1800", "mm", "171"),
            array("Half-Red Dragon Veteran", "Medium", "Humanoid", "human", "Any", "5", "1800", "mm", "180"),
            array("Hill Giant", "Huge", "Giant", "CE", "5", "1800", "mm", "155"),
            array("Mezzoloth", "Medium", "Fiend", "yugoloth", "NE", "5", "1800", "mm", "313"),
            array("Night Hag", "Medium", "Fiend", "NE", "5", "1800", "mm", "178"),
            array("Otyugh", "Large", "Aberration", "N", "5", "1800", "mm", "248"),
            array("Red Slaad", "Large", "Aberration", "CN", "5", "1800", "mm", "276"),
            array("Revenant", "Medium", "Undead", "N", "5", "1800", "mm", "259"),
            array("Roper", "Large", "Monstrosity", "NE", "5", "1800", "mm", "261"),
            array("Sahuagin Baron", "Large", "Humanoid", "sahuagin", "LE", "5", "1800", "mm", "264"),
            array("Salamander", "Large", "Elemental", "NE", "5", "1800", "mm", "266"),
            array("Shambling Mound", "Large", "Plant", "Unaligned", "5", "1800", "mm", "270"),
            array("Triceratops", "Huge", "Beast", "Unaligned", "5", "1800", "mm", "80"),
            array("Troll", "Large", "Giant", "CE", "5", "1800", "mm", "291"),
            array("Umber Hulk", "Large", "Monstrosity", "CE", "5", "1800", "mm", "292"),
            array("Unicorn", "Large", "Celestial", "LG", "5", "1800", "mm", "294"),
            array("Vampire Spawn", "Medium", "Undead", "NE", "5", "1800", "mm", "298"),
            array("Water Elemental", "Large", "Elemental", "N", "5", "1800", "mm", "125"),
            array("Werebear", "Medium", "Humanoid", "Human, Shapeshifter", "NG", "5", "1800", "mm", "208"),
            array("Wraith", "Medium", "Undead", "NE", "5", "1800", "mm", "302"),
            array("Xorn", "Medium", "Elemental", "N", "5", "1800", "mm", "304"),
            array("Young Remorhaz", "Large", "Monstrosity", "Unaligned", "5", "1800", "mm", "258"),
            array("Chasme", "Large", "Fiend", "demon", "CE", "6", "2300", "mm", "57"),
            array("Chimera", "Large", "Monstrosity", "CE", "6", "2300", "mm", "39"),
            array("Cyclops", "Huge", "Giant", "CN", "6", "2300", "mm", "45"),
            array("Drider", "Large", "Monstrosity", "CE", "6", "2300", "mm", "120"),
            array("Galeb Duhr", "Medium", "Elemental", "N", "6", "2300", "mm", "139"),
            array("Githzerai Zerth", "Medium", "Humanoid", "gith", "LN", "6", "2300", "mm", "161"),
            array("Hobgoblin Warlord", "Medium", "Humanoid", "goblinoid", "LE", "6", "2300", "mm", "187"),
            array("Invisible Stalker", "Medium", "Elemental", "N", "6", "2300", "mm", "192"),
            array("Kuo-toa Archpriest", "Medium", "Humanoid", "kuo-toa", "NE", "6", "2300", "mm", "200"),
            array("Mammoth", "Huge", "Beast", "Unaligned", "6", "2300", "mm", "332"),
            array("Medusa", "Medium", "Monstrosity", "LE", "6", "2300", "mm", "214"),
            array("Vrock", "Large", "Fiend", "demon", "CE", "6", "2300", "mm", "64"),
            array("Wyvern", "Large", "Dragon", "Unaligned", "6", "2300", "mm", "303"),
            array("Young Brass Dragon", "Large", "Dragon", "CG", "6", "2300", "mm", "105"),
            array("Young White Dragon", "Large", "Dragon", "CE", "6", "2300", "mm", "101"),
            array("Blue Slaad", "Large", "Aberration", "CN", "7", "2900", "mm", "276"),
            array("Drow Mage", "Medium", "Humanoid", "elf", "NE", "7", "2900", "mm", "129"),
            array("Giant Ape", "Huge", "Beast", "Unaligned", "7", "2900", "mm", "323"),
            array("Grick Alpha", "Large", "Monstrosity", "N", "7", "2900", "mm", "173"),
            array("Mind Flayer", "Medium", "Aberration", "LE", "7", "2900", "mm", "222"),
            array("Oni", "Large", "Giant", "LE", "7", "2900", "mm", "239"),
            array("Shield Guardian", "Large", "Construct", "Unaligned", "7", "2900", "mm", "271"),
            array("Stone Giant", "Huge", "Giant", "N", "7", "2900", "mm", "156"),
            array("Young Black Dragon", "Large", "Dragon", "CE", "7", "2900", "mm", "88"),
            array("Young Copper Dragon", "Large", "Dragon", "CG", "7", "2900", "mm", "111"),
            array("Yuan-ti Abomination", "Large", "Monstrosity", "shapechanger, yuan-ti", "NE", "7", "2900", "mm", "308"),
            array("Chain Devil", "Medium", "Fiend", "devil", "LE", "8", "3900", "mm", "72"),
            array("Cloaker", "Large", "Aberration", "CN", "8", "3900", "mm", "41"),
            array("Drow Priestess of Lolth", "Medium", "Humanoid", "elf", "NE", "8", "3900", "mm", "129"),
            array("Fomorian", "Huge", "Giant", "CE", "8", "3900", "mm", "136"),
            array("Frost Giant", "Huge", "Giant", "NE", "8", "3900", "mm", "155"),
            array("Githyanki Knight", "Medium", "Humanoid", "gith", "LE", "8", "3900", "mm", "160"),
            array("Green Slaad", "Large", "Aberration", "shapechanger", "CN", "8", "3900", "mm", "277"),
            array("Hezrou", "Large", "Fiend", "demon", "CE", "8", "3900", "mm", "60"),
            array("Hydra", "Huge", "Monstrosity", "Unaligned", "8", "3900", "mm", "190"),
            array("Mind Flayer Arcanist", "Medium", "Aberration", "LE", "8", "3900", "mm", "222"),
            array("Spirit Naga", "Large", "Monstrosity", "CE", "8", "3900", "mm", "234"),
            array("Tyrannosaurus Rex", "Huge", "Beast", "Unaligned", "8", "3900", "mm", "80"),
            array("Young Bronze Dragon", "Large", "Dragon", "LG", "8", "3900", "mm", "108"),
            array("Young Green Dragon", "Large", "Dragon", "LE", "8", "3900", "mm", "94"),
            array("Abominable Yeti", "Huge", "Monstrosity", "CE", "9", "5000", "mm", "306"),
            array("Bone Devil", "Large", "Fiend", "devil", "LE", "9", "5000", "mm", "71"),
            array("Clay Golem", "Large", "Construct", "Unaligned", "9", "5000", "mm", "168"),
            array("Cloud Giant", "Huge", "Giant", "NG or NE", "9", "5000", "mm", "154"),
            array("Fire Giant", "Huge", "Giant", "LE", "9", "5000", "mm", "154"),
            array("Glabrezu", "Large", "Fiend", "demon", "CE", "9", "5000", "mm", "58"),
            array("Gray Slaad", "Medium", "Aberration", "shapechanger", "CN", "9", "5000", "mm", "277"),
            array("Nycaloth", "Large", "Fiend", "yugoloth", "NE", "9", "5000", "mm", "314"),
            array("Treant", "Huge", "Plant", "CG", "9", "5000", "mm", "289"),
            array("Young Blue Dragon", "Large", "Dragon", "LE", "9", "5000", "mm", "91"),
            array("Young Silver Dragon", "Large", "Dragon", "LG", "9", "5000", "mm", "118"),
            array("Aboleth", "Large", "Aberration", "LE", "10", "5900", "mm", "13"),
            array("Death Slaad", "Medium", "Aberration", "shapechanger", "CE", "10", "5900", "mm", "278"),
            array("Deva", "Medium", "Celestial", "LG", "10", "5900", "mm", "16"),
            array("Guardian Naga", "Large", "Monstrosity", "LG", "10", "5900", "mm", "234"),
            array("Stone Golem", "Large", "Construct", "Unaligned", "10", "5900", "mm", "170"),
            array("Yochlol", "Medium", "Fiend", "demon, shapechanger", "CE", "10", "5900", "mm", "65"),
            array("Young Gold Dragon", "Large", "Dragon", "LG", "10", "5900", "mm", "115"),
            array("Young Red Dragon", "Large", "Dragon", "CE", "10", "5900", "mm", "98"),
            array("Behir", "Huge", "Monstrosity", "NE", "11", "7200", "mm", "25"),
            array("Dao", "Large", "Elemental", "NE", "11", "7200", "mm", "143"),
            array("Djinni", "Large", "Elemental", "CG", "11", "7200", "mm", "144"),
            array("Efreeti", "Large", "Elemental", "LE", "11", "7200", "mm", "145"),
            array("Gynosphinx", "Large", "Monstrosity", "LN", "11", "7200", "mm", "282"),
            array("Horned Devil", "Large", "Fiend", "devil", "LE", "11", "7200", "mm", "74"),
            array("Marid", "Large", "Elemental", "CN", "11", "7200", "mm", "146"),
            array("Remorhaz", "Huge", "Monstrosity", "Unaligned", "11", "7200", "mm", "258"),
            array("Roc", "Gargantuan", "Monstrosity", "Unaligned", "11", "7200", "mm", "260"),
            array("Arcanaloth", "Medium", "Fiend", "yugoloth", "NE", "12", "8400", "mm", "313"),
            array("Erinyes", "Medium", "Fiend", "devil", "LE", "12", "8400", "mm", "73"),
            array("Adult Brass Dragon", "Huge", "Dragon", "CG", "13", "10000", "mm", "105"),
            array("Adult White Dragon", "Huge", "Dragon", "CE", "13", "10000", "mm", "101"),
            array("Beholder", "Large", "Aberration", "LE", "13", "10000", "mm", "28"),
            array("Nalfeshnee", "Large", "Fiend", "demon", "CE", "13", "10000", "mm", "62"),
            array("Rakshasa", "Medium", "Fiend", "LE", "13", "10000", "mm", "257"),
            array("Storm Giant", "Huge", "Giant", "CG", "13", "10000", "mm", "156"),
            array("Ultroloth", "Medium", "Fiend", "yugoloth", "NE", "13", "10000", "mm", "314"),
            array("Vampire", "Medium", "Undead", "shapechanger", "LE", "13", "10000", "mm", "297"),
            array("Young Red Shadow Dragon", "Large", "Dragon", "CE", "13", "10000", "mm", "85"),
            array("Adult Black Dragon", "Huge", "Dragon", "CE", "14", "11500", "mm", "88"),
            array("Adult Copper Dragon", "Huge", "Dragon", "CG", "14", "11500", "mm", "111"),
            array("Beholder", "Large", "Aberration", "LE", "14", "11500", "mm", "28"),
            array("Death Tyrant", "Large", "Undead", "LE", "14", "11500", "mm", "29"),
            array("Ice Devil", "Large", "Fiend", "devil", "LE", "14", "11500", "mm", "75"),
            array("Adult Bronze Dragon", "Huge", "Dragon", "LG", "15", "13000", "mm", "108"),
            array("Adult Green Dragon", "Huge", "Dragon", "LE", "15", "13000", "mm", "94"),
            array("Death Tyrant", "Large", "Undead", "LE", "15", "13000", "mm", "29"),
            array("Mummy Lord", "Medium", "Undead", "LE", "15", "13000", "mm", "229"),
            array("Purple Worm", "Gargantuan", "Monstrosity", "Unaligned", "15", "13000", "mm", "255"),
            array("Vampire (spellcaster)", "Medium", "Undead", "shapechanger", "LE", "15", "13000", "mm", "297"),
            array("Vampire (warrior)", "Medium", "Undead", "shapechanger", "LE", "15", "13000", "mm", "297"),
            array("Adult Blue Dragon", "Huge", "Dragon", "LE", "16", "15000", "mm", "91"),
            array("Adult Silver Dragon", "Huge", "Dragon", "LG", "16", "15000", "mm", "117"),
            array("Iron Golem", "Large", "Construct", "Unaligned", "16", "15000", "mm", "170"),
            array("Marilith", "Large", "Fiend", "demon", "CE", "16", "15000", "mm", "61"),
            array("Mummy Lord", "Medium", "Undead", "LE", "16", "15000", "mm", "229"),
            array("Planetar", "Large", "Celestial", "LG", "16", "15000", "mm", "17"),
            array("Adult Blue Dracolich", "Huge", "Undead", "LE", "17", "18000", "mm", "84"),
            array("Adult Gold Dragon", "Huge", "Dragon", "LG", "17", "18000", "mm", "114"),
            array("Adult Red Dragon", "Huge", "Dragon", "CE", "17", "18000", "mm", "98"),
            array("Androsphinx", "Large", "Monstrosity", "LN", "17", "18000", "mm", "281"),
            array("Death Knight", "Medium", "Undead", "CE", "17", "18000", "mm", "47"),
            array("Dragon Turtle", "Gargantuan", "Dragon", "N", "17", "18000", "mm", "119"),
            array("Goristro", "Huge", "Fiend", "demon", "CE", "17", "18000", "mm", "59"),
            array("Demilich", "Tiny", "Undead", "NE", "18", "20000", "mm", "48"),
            array("Balor", "Huge", "Fiend", "demon", "CE", "19", "22000", "mm", "55"),
            array("Demilich", "Tiny", "Undead", "NE", "20", "24500", "mm", "48"),
            array("Ancient Brass Dragon", "Gargantuan", "Dragon", "CG", "20", "25000", "mm", "104"),
            array("Ancient White Dragon", "Gargantuan", "Dragon", "CE", "20", "25000", "mm", "100"),
            array("Pit Fiend", "Large", "Fiend", "devil", "LE", "20", "25000", "mm", "77"),
            array("Ancient Black Dragon", "Gargantuan", "Dragon", "CE", "21", "33000", "mm", "87"),
            array("Ancient Copper Dragon", "Gargantuan", "Dragon", "CG", "21", "33000", "mm", "110"),
            array("Lich", "Medium", "Undead", "Any evil", "21", "33000", "mm", "202"),
            array("Solar", "Large", "Celestial", "LG", "21", "33000", "mm", "18"),
            array("Ancient Bronze Dragon", "Gargantuan", "Dragon", "LG", "22", "41000", "mm", "107"),
            array("Ancient Green Dragon", "Gargantuan", "Dragon", "LE", "22", "41000", "mm", "93"),
            array("Lich", "Medium", "Undead", "Any evil", "22", "41000", "mm", "202"),
            array("Ancient Blue Dragon", "Gargantuan", "Dragon", "LE", "23", "50000", "mm", "90"),
            array("Ancient Silver Dragon", "Gargantuan", "Dragon", "LG", "23", "50000", "mm", "116"),
            array("Empyrean", "Huge", "Celestial", "titan", "CG or NE", "23", "50000", "mm", "130"),
            array("Kraken Gargantuan", "Monstrosity", "titan", "CE", "23", "50000", "mm", "197"),
            array("Ancient Gold Dragon", "Gargantuan", "Dragon", "LG", "24", "62000", "mm", "113"),
            array("Ancient Red Dragon", "Gargantuan", "Dragon", "CE", "24", "62000", "mm", "97"),
            array("Tarrasque Gargantuan", "Monstrosity", "titan", "Unaligned", "30", "155000", "mm", "286")
        );

        foreach ($v as $m) {

            $mon = $this->defaults;

            if ( count($m) == 9 ) {
                $mon["name"] = $m[0];
                $mon["size"] = $m[1];
                $mon["type"] = $m[2];
                $mon["tags"] = $m[3];
                $mon["alignment"] = $m[4];
                $mon["challenge"] = $m[5];
                $mon["xp"] = $m[6];
                $mon["source"] = $m[7] . ' ' . $m[8];
            }
            else if ( count($m) == 8 ) {
                $mon["name"] = $m[0];
                $mon["size"] = $m[1];
                $mon["type"] = $m[2];
                $mon["alignment"] = $m[3];
                $mon["challenge"] = $m[4];
                $mon["xp"] = $m[5];
                $mon["source"] = $m[6] . ' ' . $m[7];

                //dump($mon);
            }
            else {
                //dump($m);
            }

            //dump($mon);
            $this->add($mon);
        }
    }
}
